Input box ignores new changes if user scrolls the list #402 Loading multiple charts overrides the load data #400 Losing PositionLine when change resolution #399 uncaught exception: Internal error 0x10 while extrapolating back #397 Wrong market state #396 Callbacks overidden with multiple charts in the same window. #392 createStudy() #391 Snapshot Function Add / to the URL #383 onScreenshotReady is not a function #382 How to set the minimal price change to 2.5 #360 Resolutions is stuck when switching symbol and resolution fallback happens #308 Uncaught TypeError: Cannot read property 'updateUI' of undefined #233